
import React from 'react';
import { PredictionResult } from '../types';
import { Card } from './ui/Card';
import { Button } from './ui/Button';

interface ResultDisplayProps {
  result: PredictionResult;
  onReset: () => void;
}

export const ResultDisplay: React.FC<ResultDisplayProps> = ({ result, onReset }) => {

    const getConfidenceColor = (score: number) => {
        if (score > 0.9) return 'text-green-500';
        if (score > 0.8) return 'text-yellow-500';
        return 'text-orange-500';
    }

    const handleDownload = () => {
        alert("PDF download functionality would be implemented here.");
        window.print();
    }

  return (
    <div className="mt-8">
        <h2 className="text-3xl font-bold text-center mb-6 text-secondary dark:text-primary-light">Analysis Report</h2>
        <Card className="p-6 md:p-8">
            <div className="grid md:grid-cols-2 gap-8 items-start">
                <div>
                    <h3 className="text-2xl font-bold text-primary dark:text-primary-light">{result.psoriasisType}</h3>
                    <div className="mt-4">
                        <p className="text-lg font-semibold text-gray-700 dark:text-gray-200">Confidence Score</p>
                        <p className={`text-5xl font-bold ${getConfidenceColor(result.confidenceScore)}`}>
                            {(result.confidenceScore * 100).toFixed(1)}%
                        </p>
                    </div>
                    <div className="mt-6">
                        <h4 className="text-xl font-semibold text-gray-800 dark:text-gray-100">AI Explanation</h4>
                        <p className="text-gray-600 dark:text-gray-300 mt-2">{result.explanation}</p>
                    </div>
                </div>
                 <div>
                    <h4 className="text-xl font-semibold text-gray-800 dark:text-gray-100 mb-2">AI Focus Area (Heatmap)</h4>
                    <img 
                        src={result.heatmapUrl} 
                        alt="Grad-CAM heatmap indicating areas of interest" 
                        className="rounded-lg shadow-md w-full" 
                        aria-describedby="heatmap-desc"
                    />
                    <p id="heatmap-desc" className="text-sm text-gray-500 mt-2">This image highlights the regions the AI model focused on to make its prediction.</p>
                </div>
            </div>
            <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
                <div className="bg-yellow-100 dark:bg-yellow-900 border-l-4 border-yellow-500 text-yellow-800 dark:text-yellow-200 p-4 rounded-md" role="alert">
                    <p className="font-bold">Medical Disclaimer</p>
                    <p>This result is generated by an AI model and is for informational purposes only. It is not a substitute for a professional medical diagnosis. Please consult a qualified healthcare provider for any health concerns.</p>
                </div>
            </div>
             <div className="mt-8 flex flex-col sm:flex-row justify-center items-center gap-4">
                <Button onClick={handleDownload}>Download Report (PDF)</Button>
                <Button onClick={onReset} variant="secondary">Analyze Another Image</Button>
            </div>
        </Card>
    </div>
  );
};
